Cache direnv hook for speedup zsh

diff --git a/zsh_functions b/zsh_functions
--- a/zsh_functions
+++ b/zsh_functions
@@ -13,3 +13,28 @@ function mcdir() {
     mkdir -p "$1";
     cd "$1";
 }
+
+# Caches the output of a binary initialization command, to avoid the time to
+# execute it in the future.
+#
+# Usage: _evalcache <command> <generation args...>
+# Source: https://github.com/mroth/evalcache
+# Placed here since I don't have a plugin system in use
+function _evalcache () {
+  local cacheFile="$ZSH_EVALCACHE_DIR/init-${1##*/}.sh"
+
+  if [ "$ZSH_EVALCACHE_DISABLE" = "true" ]; then
+    eval "$("$@")"
+  elif [ -s "$cacheFile" ]; then
+    source "$cacheFile"
+  else
+    if type "$1" > /dev/null; then
+      (>&2 echo "$1 initialization not cached, caching output of: $*")
+      mkdir -p "$ZSH_EVALCACHE_DIR"
+      "$@" > "$cacheFile"
+      source "$cacheFile"
+    else
+      echo "evalcache ERROR: $1 is not installed or in PATH"
+    fi
+  fi
+}
