Set default zsh eval cache

diff --git a/zsh_functions b/zsh_functions
--- a/zsh_functions
+++ b/zsh_functions
@@ -21,20 +21,21 @@ function mcdir() {
 # Source: https://github.com/mroth/evalcache
 # Placed here since I don't have a plugin system in use
 function _evalcache () {
-  local cacheFile="$ZSH_EVALCACHE_DIR/init-${1##*/}.sh"
+    export ZSH_EVALCACHE_DIR=${ZSH_EVALCACHE_DIR:=$HOME/.cache/zsh/}
+    local cacheFile="$ZSH_EVALCACHE_DIR/init-${1##*/}.sh"
 
-  if [ "$ZSH_EVALCACHE_DISABLE" = "true" ]; then
-    eval "$("$@")"
-  elif [ -s "$cacheFile" ]; then
-    source "$cacheFile"
-  else
-    if type "$1" > /dev/null; then
-      (>&2 echo "$1 initialization not cached, caching output of: $*")
-      mkdir -p "$ZSH_EVALCACHE_DIR"
-      "$@" > "$cacheFile"
-      source "$cacheFile"
+    if [ "$ZSH_EVALCACHE_DISABLE" = "true" ]; then
+        eval "$("$@")"
+    elif [ -s "$cacheFile" ]; then
+        source "$cacheFile"
     else
-      echo "evalcache ERROR: $1 is not installed or in PATH"
+        if type "$1" > /dev/null; then
+            (>&2 echo "$1 initialization not cached, caching output of: $*")
+            mkdir -p "$ZSH_EVALCACHE_DIR"
+            "$@" > "$cacheFile"
+            source "$cacheFile"
+        else
+            echo "evalcache ERROR: $1 is not installed or in PATH"
+        fi
     fi
-  fi
 }
