feat(git): add max of characters in error message

diff --git a/config/git/hooks/commit-msg b/config/git/hooks/commit-msg
--- a/config/git/hooks/commit-msg
+++ b/config/git/hooks/commit-msg
@@ -15,7 +15,7 @@ if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|bui
 fi
 
 if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
-    echo "$RED ERROR $NORMAL Commit message is too long." >&2
+    echo "$RED ERROR $NORMAL Commit message is too long, max 72 characters." >&2
     exit 1
 fi
 exit 0
